# Generated by Django 4.2.16 on 2025-08-23 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payer_id', models.CharField(blank=True, max_length=100)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=0.99, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ipn_track_id', models.CharField(blank=True, max_length=255)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PayPal Subscription',
                'verbose_name_plural': 'PayPal Subscriptions',
                'db_table': 'payments_paypal_subscription',
            },
        ),
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payer_id', models.CharField(blank=True, max_length=100)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('receiver_email', models.EmailField(blank=True, max_length=254)),
                ('ipn_track_id', models.CharField(blank=True, max_length=255)),
                ('payment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paypalsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PayPal Payment',
                'verbose_name_plural': 'PayPal Payments',
                'db_table': 'payments_paypal_payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
