# Docker Compose for local development
# Railway doesn't use this, but useful for local testing

version: '3.8'

services:
  web:
    build: .
    command: ./start.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=eyehealth
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A mysite worker --loglevel=info --concurrency=2
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery_beat:
    build: .
    command: celery -A mysite beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
  static_volume:
