# Generated by Django 4.2.16 on 2025-09-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('google', 'Google Calendar'), ('outlook', 'Microsoft Outlook/Office 365'), ('apple', 'Apple Calendar (iCloud)'), ('exchange', 'Microsoft Exchange')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_oauth', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Provider',
                'verbose_name_plural': 'Calendar Providers',
                'db_table': 'calendar_provider',
            },
        ),
        migrations.CreateModel(
            name='UserCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('calendar_id', models.CharField(blank=True, max_length=255)),
                ('calendar_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('check_busy_periods', models.BooleanField(default=True)),
                ('respect_focus_time', models.BooleanField(default=True)),
                ('minimum_meeting_gap_minutes', models.PositiveIntegerField(default=5)),
                ('interruption_rule', models.CharField(choices=[('never', 'Never interrupt during meetings'), ('low_priority', 'Only interrupt for low priority meetings'), ('before_end', 'Interrupt 5 minutes before meeting ends'), ('between_meetings', 'Only interrupt between meetings')], default='between_meetings', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendarprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Calendar Connection',
                'verbose_name_plural': 'User Calendar Connections',
                'db_table': 'user_calendar_connection',
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
