# Generated by Django 4.2.16 on 2025-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_realtimemetrics_usersession_usersatisfactionrating_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['user', 'date'], name='analytics_d_user_id_c4a930_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystats',
            index=models.Index(fields=['date'], name='analytics_d_date_26c219_idx'),
        ),
    ]
