# Generated by Django 4.2.16 on 2025-09-17 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0003_dailystats_analytics_d_user_id_c4a930_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Usage Pattern Insight'), ('achievement', 'Achievement Insight'), ('health', 'Health Impact Insight'), ('productivity', 'Productivity Insight'), ('recommendation', 'Recommendation')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_suggestion', models.TextField(blank=True)),
                ('supporting_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('acted_on', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Insight',
                'verbose_name_plural': 'Premium Insights',
                'db_table': 'analytics_premium_insight',
                'ordering': ['-generated_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='PremiumAnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('yearly', 'Yearly Report')], max_length=20)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_work_hours', models.FloatField(default=0.0)),
                ('total_breaks', models.PositiveIntegerField(default=0)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('peak_productivity_hours', models.JSONField(default=list)),
                ('most_productive_days', models.JSONField(default=list)),
                ('break_patterns', models.JSONField(default=dict)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('estimated_eye_strain_reduction', models.FloatField(default=0.0)),
                ('estimated_productivity_boost', models.FloatField(default=0.0)),
                ('health_score', models.FloatField(default=0.0)),
                ('vs_previous_period', models.JSONField(default=dict)),
                ('vs_user_average', models.JSONField(default=dict)),
                ('vs_community_average', models.JSONField(default=dict)),
                ('is_generated', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generation_time_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Premium Analytics Report',
                'verbose_name_plural': 'Premium Analytics Reports',
                'db_table': 'analytics_premium_report',
                'ordering': ['-report_period_start'],
                'unique_together': {('user', 'report_type', 'report_period_start')},
            },
        ),
    ]
