# Generated by Django 4.2.16 on 2025-10-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_additional_analytics_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiuminsight',
            name='user',
        ),
        migrations.DeleteModel(
            name='PremiumAnalyticsReport',
        ),
        migrations.DeleteModel(
            name='PremiumInsight',
        ),
    ]
