# Generated by Django 4.2.16 on 2025-10-04 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_premiuminsight_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimemetrics',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='realtimemetrics',
            index=models.Index(fields=['-timestamp'], name='realtime_ts_idx'),
        ),
    ]
