# Generated by Django 4.2.16 on 2025-08-23 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreakData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_daily_streak', models.PositiveIntegerField(default=0)),
                ('current_weekly_streak', models.PositiveIntegerField(default=0)),
                ('best_daily_streak', models.PositiveIntegerField(default=0)),
                ('best_weekly_streak', models.PositiveIntegerField(default=0)),
                ('last_session_date', models.DateField(blank=True, null=True)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('total_sessions_completed', models.PositiveIntegerField(default=0)),
                ('total_break_time_minutes', models.PositiveIntegerField(default=0)),
                ('average_session_length', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Streak Data',
                'verbose_name_plural': 'User Streak Data',
                'db_table': 'accounts_userstreakdata',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('streak_7', '7 Day Streak'), ('streak_30', '30 Day Streak'), ('streak_100', '100 Day Streak'), ('early_bird', 'Early Bird (5 AM - 9 AM sessions)'), ('night_owl', 'Night Owl (6 PM - 12 AM sessions)'), ('weekend_warrior', 'Weekend Warrior'), ('session_master', '1000 Sessions Complete'), ('eye_health_champion', 'Perfect Week')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'db_table': 'accounts_achievement',
                'unique_together': {('user', 'achievement_type')},
            },
        ),
    ]
