# Generated by Django 4.2.16 on 2025-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_test_premium_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='is_premium_only',
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['user', 'achievement_type'], name='accounts_ac_user_id_72130b_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['earned_at'], name='accounts_ac_earned__50f71e_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='accounts_us_user_id_806298_idx'),
        ),
    ]
