# Generated by Django 4.2.16 on 2025-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_challenge_is_premium_only_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userlevel',
            constraint=models.CheckConstraint(check=models.Q(('current_level__gte', 1)), name='level_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='userlevel',
            constraint=models.CheckConstraint(check=models.Q(('total_experience_points__gte', 0)), name='exp_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='userlevel',
            constraint=models.CheckConstraint(check=models.Q(('experience_to_next_level__gt', 0)), name='next_exp_gt_0'),
        ),
    ]
