# Generated by Django 4.2.16 on 2025-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_userlevel_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='experience_to_next_level',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='total_experience_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
