# Generated by Django 4.2.16 on 2025-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_integer_overflow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.CheckConstraint(check=models.Q(('target_value__gt', 0)), name='challenge_target_gt_0'),
        ),
    ]
