# Constants for the EyeHealth 20-20-20 SaaS application

# Timer Constants
DEFAULT_WORK_INTERVAL_MINUTES = 20
DEFAULT_BREAK_DURATION_SECONDS = 20
DEFAULT_LONG_BREAK_MINUTES = 5

# Subscription Limits
FREE_DAILY_INTERVAL_LIMIT = 12  # 12 intervals = 4 hours of work time (optimized for conversion)
PREMIUM_DAILY_INTERVAL_LIMIT = 0  # 0 means unlimited

# Legacy session limits (deprecated)
FREE_DAILY_SESSION_LIMIT = 5
PREMIUM_DAILY_SESSION_LIMIT = 0

# Pricing
PREMIUM_MONTHLY_PRICE_USD = 0.99

# Rate Limiting
SESSION_RATE_LIMIT = '10/m'
BREAK_RATE_LIMIT = '20/m'
SYNC_RATE_LIMIT = '30/m'
PAYMENT_RATE_LIMIT = '5/m'

# Achievement Constants
STREAK_ACHIEVEMENTS = {
    'streak_7': 7,
    'streak_30': 30,
    'streak_100': 100,
}

SESSION_MASTER_THRESHOLD = 1000
EARLY_BIRD_SESSIONS_REQUIRED = 10
NIGHT_OWL_SESSIONS_REQUIRED = 10

# Time Ranges (24-hour format)
EARLY_BIRD_START_HOUR = 5
EARLY_BIRD_END_HOUR = 9
NIGHT_OWL_START_HOUR = 18
NIGHT_OWL_END_HOUR = 23

# Activity Tracking
ACTIVE_USER_TIMEOUT_MINUTES = 5
BREAK_ACTIVE_TIMEOUT_MINUTES = 2

# Analytics
DEFAULT_STATISTICS_DAYS = 30
MAX_RECENT_SESSIONS = 10
MAX_RECENT_ACTIVITIES = 10

# Sound Settings
DEFAULT_SOUND_VOLUME = 0.5
MIN_SOUND_VOLUME = 0.0
MAX_SOUND_VOLUME = 1.0

# Notification Settings
DEFAULT_NOTIFICATION_SOUND = 'gentle'

# Email Settings
DEFAULT_FROM_EMAIL_NAME = 'EyeHealth 20-20-20'
DEFAULT_FROM_EMAIL_DOMAIN = 'noreply@eyehealth2020.com'

# Cache Settings
USER_STATS_CACHE_TIMEOUT = 300  # 5 minutes
REALTIME_METRICS_UPDATE_INTERVAL = 60  # 1 minute

# Security Settings
MAX_LOGIN_ATTEMPTS = 5
LOCKOUT_TIME_HOURS = 1

# File Upload Settings
MAX_PROFILE_IMAGE_SIZE_MB = 5
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif']

# API Settings
DEFAULT_API_PAGE_SIZE = 20
MAX_API_PAGE_SIZE = 100

# Webhook Settings
WEBHOOK_TIMEOUT_SECONDS = 30
MAX_WEBHOOK_RETRIES = 3