# Generated by Django 4.2.16 on 2025-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_add_sound_settings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['user', 'start_time'], name='timer_sessi_user_id_5141ab_idx'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['user', 'is_active'], name='timer_sessi_user_id_81aea8_idx'),
        ),
        migrations.AddIndex(
            model_name='timersession',
            index=models.Index(fields=['start_time'], name='timer_sessi_start_t_3df887_idx'),
        ),
    ]
