# Generated by Django 4.2.16 on 2025-09-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_timersession_timer_sessi_user_id_5141ab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimersettings',
            name='preferred_break_duration',
            field=models.PositiveIntegerField(choices=[(10, '10 seconds - Quick break'), (20, '20 seconds - Standard 20-20-20'), (30, '30 seconds - Extended break'), (60, '1 minute - Long break')], default=20, help_text='Preferred break duration for smart break system'),
        ),
        migrations.AddField(
            model_name='usertimersettings',
            name='smart_break_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
