# Generated by Django 4.2.16 on 2025-09-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timer', '0004_usertimersettings_preferred_break_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('break_duration', 'Break Duration Preference'), ('interruption_timing', 'Interruption Timing Feedback'), ('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('general', 'General Feedback'), ('break_compliance', 'Break Compliance Feedback')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(blank=True, help_text='1-5 rating scale', null=True)),
                ('timer_session_id', models.PositiveIntegerField(blank=True, null=True)),
                ('break_record_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('user_agent', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback Entries',
                'db_table': 'user_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'feedback_type'], name='user_feedba_user_id_601d8c_idx'), models.Index(fields=['feedback_type', 'status'], name='user_feedba_feedbac_7ed9c1_idx'), models.Index(fields=['created_at'], name='user_feedba_created_1f96f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='BreakPreferenceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_break_duration', models.PositiveIntegerField(default=20)),
                ('actual_average_break_duration', models.FloatField(default=0.0)),
                ('break_completion_rate', models.FloatField(default=0.0)),
                ('preferred_break_times', models.JSONField(default=list)),
                ('most_skipped_times', models.JSONField(default=list)),
                ('compliant_breaks_percentage', models.FloatField(default=0.0)),
                ('looks_at_distance_rate', models.FloatField(default=0.0)),
                ('reported_eye_strain_reduction', models.FloatField(blank=True, null=True)),
                ('productivity_impact_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('analysis_start_date', models.DateField()),
                ('analysis_end_date', models.DateField()),
                ('total_sessions_analyzed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Break Preference Analytics',
                'verbose_name_plural': 'Break Preference Analytics',
                'db_table': 'break_preference_analytics',
                'unique_together': {('user', 'analysis_start_date', 'analysis_end_date')},
            },
        ),
    ]
