# Generated by Django 4.2.16 on 2025-09-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_additional_performance_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='breakrecord',
            index=models.Index(fields=['user', 'break_start_time'], name='timer_break_user_id_6b0cad_idx'),
        ),
        migrations.AddIndex(
            model_name='breakrecord',
            index=models.Index(fields=['session', 'break_completed'], name='timer_break_session_c1c68f_idx'),
        ),
        migrations.AddIndex(
            model_name='breakrecord',
            index=models.Index(fields=['break_start_time', 'break_completed'], name='timer_break_break_s_d8cb59_idx'),
        ),
        migrations.AddIndex(
            model_name='breakrecord',
            index=models.Index(fields=['user', 'break_completed', 'break_duration_seconds'], name='timer_break_user_id_76ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='timerinterval',
            index=models.Index(fields=['session', 'status'], name='timer_inter_session_0a4143_idx'),
        ),
        migrations.AddIndex(
            model_name='timerinterval',
            index=models.Index(fields=['start_time', 'status'], name='timer_inter_start_t_b609ea_idx'),
        ),
        migrations.AddIndex(
            model_name='timerinterval',
            index=models.Index(fields=['session', 'interval_number'], name='timer_inter_session_1a91c6_idx'),
        ),
    ]
