# Generated by Django 4.2.16 on 2025-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_breakrecord_timer_break_user_id_6b0cad_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timersession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='unique_active_session_per_user'),
        ),
    ]
